config/routes.rb
Rails.application.routes.draw do
  get 'manager/main'

  get 'manager/draw_rates'

  get 'manager/top_dishes'

  get 'waiter/orderStatus'
  post 'waiter/updateOrderStatus'
  post 'waiter/updateStatusOrders2'
  get 'waiter/takeOrder'
  get 'waiter/tables'
  post 'cook/postOrder'
  post 'waiter/postOrders'
  get 'cook/orders'
  get 'hosts/checkin'
  get 'hosts/checkout'
  post 'hosts/updateStatusTables'
  post 'hosts/TabelBill'
  post 'hosts/rate'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
#  get 'cook' => 'cooks#new'
  get 'manager' => 'managers#new'
#  get 'waiter' => 'waiters#new'
  get 'host' => 'hosts#new'
  get 'signup'  => 'employees#new'
  resources :employees

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_secure_password
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :meal


end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/controllers/cook_controller.rb
class CookController < ApplicationController
  before_action :require_cook, only: [:postOrder, :orders ]
  protect_from_forgery

  def orders
  	@orders = Order.where("status": 0)
  end


  def postOrder
    if params[:order].nil?
    else
      done = params[:order].keys
      updateOrderStatus(done)
    end
  	redirect_to "/cook/orders"
  end

  def updateOrderStatus(done)
    for i in 0..done.length-1
      @order = Order.find(done[i])
      @order.update(:status => 1)
    end
  end

end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
  before_action :require_host, only: [:new , :TabelBill, :checkin ,:updateStatusTables,:checkout]
  protect_from_forgery
  def new
    @avail_tables =   Table.where(status:0 )
    @busy_tables =   Table.where(status:1 )
  end


    def checkin
     @tabels=Table.select('id,status,name').where(status: 0)
    end

    def updateStatusTables
      p keyss = params[:tabel_id]
      @TabelId=Table.find(keyss)
      @TabelId.update(status: 1); #update taple as busy
    redirect_to hosts_checkin_path
    end



    def checkout
       @checkOutTabels=Table.select('id,status,name').where(status: 1)
    end

      def TabelBill
    #<%= collection_select(:table_id, @stars, :id, :num_stars)%>

       keyss = params[:tabel_id]
       @myID = params[:tabel_id]
       @orders= Order.select('meal_id,status').where(table_id: keyss)
            @TabelId=Table.find(keyss)
            @TabelId.update(status: 0); #update taple as free

       p @orders

       @Details= []
       @sum=0.0;
       i=0
       while  @orders[i]!= nil
       p bill= Meal.select('name,price').where(id: @orders[i].meal_id)
       @sum=@sum+bill[0].price
            mm=Meal.new;

       mm.name=bill[0].name
       mm.price=bill[0].price
       @Details << mm

       i = i+1

       end
        #..........
        Order.where(:table_id => keyss).destroy_all
    end

    def rate

      rateVal = params[:rateVal]
      #id = params[:table_id]
      i = 0
      @current = Rating.where(num_stars: 1).take
      if(rateVal == "1")
       @current = Rating.where(num_stars: 1).take
       i=1
      end
      if(rateVal == "2")
         @current = Rating.where(num_stars: 2).take
          i=1
        end
         if(rateVal == "3")
           @current = Rating.where(num_stars: 3).take
            i=1
        end
         if(rateVal == "4")
           @current = Rating.where(num_stars: 4).take
            i=1
        end
         if(rateVal == "5")
           @current = Rating.where(num_stars: 5).take
            i=1
        end
      @noTimes = @current.num_times_rated;
       if(@noTimes < 0 )
        @noTimes = 1
      else
        @noTimes = @noTimes + 1
      end
      if(i == 1)
      @current.update(num_times_rated:@noTimes )
    end
      redirect_to "/hosts/checkout"
    end
end

app/controllers/waiter_controller.rb
class WaiterController < ApplicationController
  before_action :require_waiter, only: [:tables, :postOrders , :takeOrder ,:orderStatus, :updateOrderStatus]
  protect_from_forgery



def saveOrder( table_id,mealId)
  object = Order.new(:status => 0 , :table_id => table_id , :meal_id => mealId)
  object.save
end

def tables
 @tables = Table.all
end

def takeOrder
 @meals = Meal.all

 @table_id = params[:tableId]

end

def postOrders
  if params[:orders].nil?
  else
  meals = params[:orders].keys
  quantity = params[:repitations]
  table_id = params[:table_id]
  puts table_id
  for i in 0..meals.length-1
    mealId = meals[i]
    for j in 1..quantity[meals[i]].to_i
      saveOrder(table_id, mealId)
      updateTimesMealOrdered(mealId)
    end
  end
  redirect_to "/waiter/tables"
  end
end

def updateTimesMealOrdered(mealId)
  @meal = Meal.find(mealId)
  number_times_ordered = @meal[:number_times_ordered] +1
  @meal.update(:number_times_ordered => number_times_ordered)
end

def orderStatus
  @orderStat = Order.select('id,status,meal_id,table_id').where(status: 1)
end

def updateOrderStatus
if params[:order].nil?
else
  keyss = params[:order].keys
    i = 0
    while keyss[i] != nil
      @order = Order.find(keyss[i])
      @order.update(:status => 2)
      i = i+1
    end
  end
  redirect_to "/waiter/tables"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cook_helper.rb
module CookHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/manager_helper.rb
module ManagerHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/take_helper.rb
module TakeHelper
end

app/helpers/waiter_helper.rb
module WaiterHelper
end

app/helpers/waiters_helper.rb
module WaitersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantAutomationSystem</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <style>
      table {
              font-weight: bold;
              border-collapse: collapse;
              width: 100%;
              border: 1px solid black;

          }

          th, td {
              text-align: left;
              padding: 8px;
              border: 1px solid black;

          }


          th {
              background-color: #005f5f;
              color: white;
          }
          body {
            margin: 0;
            padding: 0;
            <% if current_employee %>
              background-image: url(/assets/farine.jpg);
              background-repeat:no-repeat;
              background-size:cover;
            <%else%>
              background-image: url(/assets/back.jpg);
              background-repeat:no-repeat;
              background-size:cover;
            <%end%>
          }
          .button {
              background-color: #4CAF50; /* Green */
              border: none;
              color: white;
              padding: 16px 32px;
              text-align: center;
              text-decoration: none;
              display: inline-block;
              font-size: 16px;
              margin: 4px 2px;
              -webkit-transition-duration: 0.4s; /* Safari */
              transition-duration: 0.4s;
              cursor: pointer;
          }
          .button5 {
              background-color: white;
              color: black;
              border: 2px solid #555555;
              border-radius: 8px;
          }

          .button5:hover {
              background-color: #555555;
              color: white;
              box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24), 0 17px 50px 0 rgba(0,0,0,0.19);
          }

          .nav ul {
            list-style: none;
            background-color: #444;
            padding: 0;
            margin: 0;
            overflow: hidden;

          }
          .nav li {
            font-family: 'Oswald', sans-serif;
            font-size: 1em;
            line-height: 40px;
            height: 40px;
            border-bottom: 1px solid #888;
          }

          .nav a {
            text-decoration: none;
            color: #fff;
            display: block;
            transition: .3s background-color;
          }

          .nav a:hover {
            background-color: #005f5f;
          }

          .nav a.active {
            background-color: #fff;
            color: #444;
            cursor: default;
          }

          @media screen and (min-width: 600px) {
            .nav li {
              width: 120px;
              border-bottom: none;
              height: 50px;
              line-height: 50px;
              font-size: 1.4em;
            }

            /* Option 1 - Display Inline */
            .nav li {
              display: inline-block;
              margin-right: -4px;
            }

            /* Options 2 - Float
            .nav li {
              float: left;
            }
            .nav ul {
              overflow: auto;
              width: 600px;
              margin: 0 auto;
            }
            .nav {
              background-color: #444;
            }
            */
          }
        </style>
  </head>
  <body>
    <header >
       <% if current_employee %>
       <div class="nav" >

              <% if current_employee.position.eql? "host" %>
                       <ul >
                         <li style="float:left;color: #005f5f ;margin-left:40px;font-size:1.8em;"><%= current_employee.position %></li>
                         <li> <%= link_to("Check In","/hosts/checkin") %> </li>
                         <li> <%= link_to("Check Out","/hosts/checkout") %> </li>
                         <li> <%= link_to("Tables","/host") %> </li>

                         <li style="float:right;" ><%= link_to "Log out", logout_path, method: "delete" %></li>
                       </ul>
              <% elsif current_employee.position.eql? "manager" %>
                      <ul >
                        <li style="float:left;color: #005f5f ;margin-left:40px;font-size:1.8em;"><%= current_employee.position %></li>

                        <li style="margin-left:70px;"> <%= link_to "Ratings",manager_draw_rates_path%> </li>
                        <li>  <%= link_to "Top Dishes",manager_top_dishes_path%> </li>
                        <li style="float:right;" ><%= link_to "Log out", logout_path, method: "delete" %></li>
                      </ul>
              <% elsif current_employee.position.eql? "waiter" %>

                      <ul >
                        <li style="float:left;color: #005f5f ;margin-left:40px;font-size:1.8em;"><%= current_employee.position %></li>
                        <li><%= link_to "Deliveries",waiter_orderStatus_path%></li>
                        <li><%= link_to "New Order",waiter_tables_path%></li>
                        <li style="float:right;" ><%= link_to "Log out", logout_path, method: "delete" %></li>
                      </ul>
              <% elsif current_employee.position.eql? "cook" %>
                        <ul >
                          <li style="float:left;color: #005f5f ;margin-left:40px;font-size:1.8em;"><%= current_employee.position %></li>
                          <li style="float:right;" ><%= link_to "Log out", logout_path, method: "delete" %></li>
                        </ul>

              <%else%>
              <% end %>
            </div>

       <%else%>

       <% end %>
   </header>
<br/>
<br/>


    <%= yield %>
  </body>
</html>